/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e0abf22f-b09b-4285-b988-dca9bed1dc35",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_uB1vYdCur",
    "aws_user_pools_web_client_id": "15mgqkq9moug2o93l9h3pddsgr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://qfbbflbibvd4ne2kzd5ovec26y.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
