/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:78776a93-787a-4eba-a174-c5217b3a3736",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_VocYw3W2j",
    "aws_user_pools_web_client_id": "3g2ssuojrj28u3n7mva8q6luok",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://uw2zprehavb23mriypwziezbou.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
