/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b57f5d8c-67cf-4da8-8005-5b6d35167c82",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YsyANDdQb",
    "aws_user_pools_web_client_id": "4pdbiujfc6660755u8q10asrg8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yfwsdowqubbkvlf5c3q5jihjqa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
